[package]
name = "rustyc2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]

name = "rustyc2"
path = "src/main.rs"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
